name: Debug Secrets

on:
  # This allows us to run it manually
  workflow_dispatch:

jobs:
  check-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Check if METRICS_TOKEN is set
        # This step creates an environment variable that is 'True' if the secret is not empty
        env:
          METRICS_TOKEN_IS_SET: ${{ secrets.METRICS_TOKEN != '' }}
        # This step prints the result
        run: |
          echo "Checking for repository secret METRICS_TOKEN..."
          echo "Is the secret available? 👉 ${{ env.METRICS_TOKEN_IS_SET }}"
          if [ "${{ env.METRICS_TOKEN_IS_SET }}" = "True" ]; then
            echo "✅ Success: The secret is configured and accessible by the workflow."
          else
            echo "❌ ERROR: The secret is NOT configured correctly. Please delete and recreate the secret."
            exit 1
          fi
