name: Update README with Recent GitHub Activity
on:
  schedule:
    - cron: '0 */4 * * *' # Runs every 4 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update README with recent activity
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          # The URL of your public GitHub activity feed
          feed_list: "https://github.com/lucianommartins.atom"
          # How many items to list
          max_post_count: 15
          # The date format for each item
          date_format: "dd/mm/yyyy"
          # The template for each line
          template: "- $date: $title<br>"
          # The name of the comment markers in your README
          comment_tag_name: "GITHUB_ACTIVITY"
          # The file to update
          readme_file: "README.md"
